### ISSUE TITLE
Formatting issue and/or confusing example

### ISSUE THREAD

**Issue by kwebster2** [learn-co-curriculum/js-basics-logical-operators-readme#2]
The following part of the lesson is hard to comprehend and I think might be intended for a snippet with formatting:

`| Left side | Right side | Return value | Truthiness of return value | |-----------|----------------|--------------|----------------------------| | Truthy | Doesn't matter | Left side | Truthy | | Falsy | Truthy | Right side | Truthy | | Falsy | Falsy | Right side | Falsy |`

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @kwebster2 .

We have updated the materials and believe your issue to have been resolved.  Missing some spacing on the markdown had broken our table!

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
