### ISSUE TITLE
Table displaying issue

### ISSUE THREAD

**Issue by kheyro** [learn-co-curriculum/js-basics-logical-operators-readme#3]
Hello, the table here doesn't display right, | Left side | Right side | Return value | Truthiness of return value | |-----------|----------------|--------------|----------------------------| | Falsy | Doesn't matter | Left side | Falsy | | Truthy | Falsy | Right side | Falsy | | Truthy | Truthy | Right side | Truthy |

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
