### ISSUE TITLE
Easy typo to fix!

### ISSUE THREAD

**Issue by MiriamPeskowitz** [learn-co-curriculum/js-basics-logical-operators-readme#6]
CONCLUCION --
Logical operators in Javascript are the powerful backbone on which most website logic is based. Once you understand how to control the different options available to you, the sky's the limit!

Should be Conclusion -- my writer's eye catches these things.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @MiriamPeskowitz.

We have updated the materials, fixed this typo, and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
